### ISSUE TITLE
Estimation process unstable

### ISSUE THREAD

**Issue by JGONGSQ** [timothyb0912/pylogit#10]
Hi,

When I try run your code with my sample data, parameter coefficients are not stable, not sure why. Can you have a look? Sometimes even the coefficient sign would be changed as well. Such as my "Male" variable, could be both positive and negative coefficients. Can you explain why? Do you have some random "input" in your estimation process?

**Comment by timothyb0912** [comment]
Which code are you trying to use? Posting a link to a gist where I can see what you've done would be useful. Alternatively posting the code you've used and a link to your data would be equally helpful.

The only code that has random input in the estimation process is the mixed logit code that uses maximum simulated likelihood for estimation. Even then, you can set the seed in the estimation so that results are constant across repeated estimations.

In general, if you have highly correlated variables and you ever-so-slightly change your specifications, then parameter signs may flip and coefficient magnitudes may not be very stable.
