### ISSUE TITLE
LinAlgError: singular matrix (with covariant features + ridge)

### ISSUE THREAD

**Issue by georgewambold** [timothyb0912/pylogit#38]
I'm getting a `numpy.linalg.linalg.LinAlgError: singular matrix` error from [line 1216 of base_multinomial_cm_v2](https://github.com/timothyb0912/pylogit/blob/master/pylogit/base_multinomial_cm_v2.py#L1216)

I'm getting these errors at what seems like random (I am setting numpy.random.seed(1) before I train the model). Note I am working with a feature matrix that has covariant features, but I'm setting the ridge parameter of `fit_mle`. 

Here's small example of what I think is causing the issue.

```
import numpy as np
import pandas as pd
import pylogit as pl

from collections import OrderedDict

np.random.seed(1)
# x is a valid feature
x = np.array([1,2,3,1.5,3.5])

# x_redundant is a redundant feature
x_redundant = x * -1

fake_df = pd.DataFrame({"obs_id": [1, 1, 1, 2, 2],
                        "alt_id": [1, 2, 3, 1, 3],
                        "choice": [0, 1, 0, 0, 1],
                        "x": x,
                        "x_redundant": x_redundant,
                        "intercept": [1 for i in range(5)]})

specification = OrderedDict()
specification['x'] = 'all_same'
specification['x_redundant'] = 'all_same'


model = pl.create_choice_model(
    data = fake_df,
    obs_id_col='obs_id',
    alt_id_col='alt_id',
    choice_col='choice',
    specification=specification,
    model_type='MNL'
)

model.fit_mle(np.zeros(2))
```

If I set `model.fit_mle(np.zeros(2), ridge=0.8)` the error doesn't get raised in this example, yet in my code I'm setting the ridge=0.8 and the error still gets raised. 

I read a few articles/cross-validated posts about singular matrices, but I'm still figuring out what it means. I wish I could be more descriptive in this issue.

Thanks for the help.

**EDIT:** 
Here's a screenshot of my hessian when I'm getting the error: 
![](https://i.imgur.com/pLvX64g.png)

**Comment by timothyb0912** [comment]
@georgewambold this behavior is expected.

Your model is not identified because x and x_redundant have a perfect linear dependence. As a result, there are an infinite number of coefficient values that would lead to the same maximum likelihood value.

No error gets raised when you use `model.fit_mle(np.zeros(2), ridge=0.8)` because ridge regression allows you to estimate coefficients even when one's hessian is singular.

PyLogit is not set up to check one's model specification for identification, mostly because I think would be very complex to do so. The onus is on the user to a priori make sure that they are specifying identified models.

**Comment by timothyb0912** [comment]
Also, there is no need to set a random seed here. None of the models in pylogit, except for mixed logit, have randomness in the training procedure. On top of that, your example uses deterministic values. As a result the random seed does nothing.

**Comment by georgewambold** [comment]
Thanks for the response!
 
My problem is that I'm getting a `LinAlgError` even with a ridge parameter set. I couldn't find a way to recreate the error with a code snippet, because it seems to happen somewhat randomly in my code. 

> "ridge regression allows you to estimate coefficients even when one's hessian is singular (not that you should...)." 

Why not? I thought one of the uses of penalized regression was to get rid of redundant/covariant features. 

Thanks again for your time. I appreciate that this is an open source project and that you're giving your time and knowledge away for free. Thank you for that.

**Comment by timothyb0912** [comment]
@georgewambold You're right, you may definitely still want to estimate coefficients. What I should have said was that you probably don't want to use normal approximations to the asymptotic sampling distribution when your model is not identified. The resulting parameter uncertainty estimates are not correct because penalized regression changes not just the variance of one's sampling distribution (as perhaps captured by the penalized hessian) but also the mean of one's sampling distribution as well.

Re the random `LinAlgError`s, If you're using an unidentified model, it may be that depending on the precise dataset being used, the ridge penalty is not strong enough to produce an invertible hessian. Either way, if one is using ridge regression, the uncertainty estimates encoded in the estimation results are incorrect. You may be best off simply doing something along the lines of
```
mnl_model_results = mnl_model.fit_mle(init_values, just_point=True)
mnl_mle_params = mnl_model_results['x']
param_list = [mnl_mle_params, None, None, None]
predictions = mnl_model.predict(prediction_df, param_list=param_list)
```

If using a model other than MNL, then one would need to modify the `param_list` accordingly. See the docstring of the `.predict()` method for details on how to create an appropriate `param_list` argument.

Re the time give-away: no worries, you're welcome! User supplied pull-requests that fix problems that you find are always most appreciated!
