### ISSUE TITLE
Add method for training in batches to avoid memory errors

### ISSUE THREAD

**Issue by seandickert** [timothyb0912/pylogit#9]
Awesome package!  Looking forward to probit models :)

Hard for me to provide samples at the moment, but for larger datasets (~10000 observations with an average of 10 alternatives per observation) instantiating the mapping matrices can raise a memory error.  This was on a 32gb box.  I can't get to the exact call at the moment, but basically memory spikes for one call to allocate a massive matrix.

A batch option to iteratively calculate the utilities would be great.

**Comment by timothyb0912** [comment]
Hey @seandickert, sorry for the super delayed responses. Dissertation writing has taken over =/.

If you clone the repo, I actually included a fix ([see here](https://github.com/timothyb0912/pylogit/commit/0bb35501342f32f87cc5cfd470a2b445b4fa41bc)) that should get rid of any issues regarding the instantiation of the mapping matrices. I haven't pushed a new version to pypy yet because I want to include a few more enhancements, but that should help for now.

A further issue will be the fact that I compute the hessian using matrix multiplication of huge matrices (dP_dV is num_rows_in_design by num_rows_in_design). That too causes memory issues with larger datasets. Perhaps there needs to be something that will compute the hessian using a for loop instead.

If you want to fork the repo, take a stab at making things work for your use case, and then submit a pull-request, that would be a great help!

**Comment by timothyb0912** [comment]
Closing in favor of continuing any discussion on [Issue 25](https://github.com/timothyb0912/pylogit/issues/25).
